export const appRoute = {
  default: "/",
  signUp: "/sign-up",
  dashboard: "/dashboard",
  experience: "/experience",
  companyDetails: "/company-details",
  roleSelection: "/role-selection",
  spotLightOnScience: "/spotlight-on-science",
  productDetails: "/product-details",
  exploreAllProducts: "/explore-all-products",
  sensoryBarExp: "/sensory-bar-experience",
  expressMakeover: "/express-makeover",
  listOfSuppliers: "/list-of-suppliers",
  supplierDetails: "/supplier-details",
};
export const protectedRoutes = [appRoute.dashboard];
export const unProtectedRoutes = [appRoute.signUp];
export const imagesPath = {
  azelisLogo: "/icon/azelis-logo.svg",
  bgMain: "/icon/bg-main.svg",
  conceptFormulation: "/icon/formulation-icon.svg",
  sensoryBar: "/icon/sensory-bar-icon.svg",
  novelIngredients: "/icon/novel-ingredients-icon.svg",
  arrow: "/icon/arrow.svg",
  azelisBlueLogo: "/icon/Azelis-blue-logo.svg",
  mildMighty: "/icon/mild-and-mighty.svg",
  grabGo: "/icon/grab-go.svg",
  unwind: "/icon/unwind-clock.svg",
  popGlamour: "/icon/pop-glamour.svg",
  vectorExploreAll: "/icon/vector-explore-all.svg",
  vectorExploreAllW: "/icon/vector-explore-all-white.svg",
  backArrow: "/icon/back-arrow.svg",
  detailsPageImg2: "/icon/details-Page-img-2.svg",
  detailsPageImg3: "/icon/details-Page-img-3.svg",
  detailsPageImg4: "/icon/details-Page-img-4.svg",
  detailsPageImg5: "/icon/details-Page-img-5.svg",
  detailsPageBg: "/icon/details-page-bg.svg",
  featureBullets: "/icon/feature-bullets.svg",
  prevArrow: "/icon/prev-arrow.svg",
  nextArrow: "/icon/next-arrow.svg",
  morningBoostIcon: "/icon/morning-boost-icon.svg",
  expressMakeoverIcon: "/icon/express-makeover-icon.svg",
  unwindYourSensesIcon: "/icon/unwind-your-senses-icon.svg",
  back: "/icon/back.svg",
  prodImg: "/icon/prodImg.svg",
  milk: "/icon/milk.svg",
  flash: "/icon/flash.svg",
  music: "/icon/music.svg",
  prev: "/icon/prevbtn.svg",
  play: "/icon/playbtn.svg",
  next: "icon/next.svg",
  folder: "icon/folder.svg",
  expAllWhiteVector: "icon/expAllWhiteVector.svg",
  file: "icon/fileicon.svg",
  download: "icon/downl.svg",
  pause: "icon/pause.svg",
  contact: "icon/contact.svg",
  contactWhite: "icon/contact-white.svg",

};

export const bgImagesPath = {
  bgMildMighty: "/images/bg-mild-mighty.jpg",
  bgGrabGo: "/images/bg-grab-go.jpg",
  bgUnwindClock: "/images/bg-unwind.jpg",
  bgSpotlight: "/images/bg-spotlight.jpg",
  bgPopGlamour: "/images/bg-pop-glamour.jpg",
  azelisLogo: "/icon/azelis-logo.svg",
  back: "/icon/back.svg",
  prodImg: "/icon/prodImg.svg",
  milk: "/icon/milk.svg",
  detailsPageImg1: "/images/details-Page-img-1.jpg",
  morningBoostBg: "/images/morning-boost-bg.jpg",
  expressMakeoverBg: "/images/express-makeover-bg.jpg",
  unwindYourSensesBg: "/images/unwind-your-senses-bg.jpg",
};
